import Navbar from "./../components/Navbar";
import "./globals.css";
import Provider from "./../SessionProvider";
import Footer from "./../components/Footer";
import backgroundImage from "./../../public/wood1.webp";

export const metadata = {
  title: "Blog Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          className="text-white"
          style={{
            backgroundImage: `url(${backgroundImage.src})`,
            position: "relative",
            backgroundPosition: "center",
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            width: "100vw",
            height: "100%",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Provider>
            <Navbar />
            {children}
            <Footer />
          </Provider>
        </div>
      </body>
    </html>
  );
}
